### ISSUE TITLE
Breakpoint via C calls dont work

### ISSUE THREAD

**Issue by StiviiK** [Jusonex/MTATD#15]
If you set an breakpoint in a LUA-Function which get called via a C (MTA-API) function, the breakpoint doesn't work!
Example:
```
addCommandHandler("abcd", function()
  print("Hi") -- Breakpoint is set here
end)
```
When typing "abcd", "Hi" gets printed and not stopped at the breakpoint.

**Comment by jushar** [comment]
I think it's fixed. Please re-test with the upcoming version.

**Comment by StiviiK** [comment]
Seems fixed! 👍
